package gui;

import command.*;

public class price extends javax.swing.JFrame {
    public price() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpayroll = new javax.swing.JLabel();
        txtcom = new javax.swing.JLabel();
        txttsal = new javax.swing.JLabel();
        llname = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel7.setText("Saler :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(580, 0, 41, 40);

        txtpayroll.setBackground(new java.awt.Color(102, 102, 255));
        txtpayroll.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txtpayroll.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtpayrollAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(txtpayroll);
        txtpayroll.setBounds(520, 300, 240, 70);

        txtcom.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txtcom.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtcomAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(txtcom);
        txtcom.setBounds(520, 460, 230, 80);

        txttsal.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txttsal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txttsalAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(txttsal);
        txttsal.setBounds(520, 620, 240, 80);

        llname.setText("111111111111111");
        llname.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                llnameAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(llname);
        llname.setBounds(760, 10, 140, 20);

        lname.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lnameAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(lname);
        lname.setBounds(630, 10, 110, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/payroll.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 280, 270, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/ปก.PNG"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 900, 270);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/com.PNG"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 450, 250, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/sum.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 610, 295, 100);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/summit.PNG"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 790, 190, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/55555.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 250, 900, 650);

        setSize(new java.awt.Dimension(917, 949));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lnameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lnameAncestorAdded
        lname.setText(login.getName());
    }//GEN-LAST:event_lnameAncestorAdded

    private void llnameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_llnameAncestorAdded
        llname.setText(login.getlanme());
    }//GEN-LAST:event_llnameAncestorAdded

    private void txtpayrollAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtpayrollAncestorAdded
        String sal = Float.toString(login.getSal());
        txtpayroll.setText(sal);
    }//GEN-LAST:event_txtpayrollAncestorAdded

    private void txtcomAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtcomAncestorAdded
        String com = Float.toString(login.getComm());
        txtcom.setText(com);
    }//GEN-LAST:event_txtcomAncestorAdded

    private void txttsalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txttsalAncestorAdded
        String tsal = Float.toString(login.getTsal());
        txttsal.setText(tsal);
    }//GEN-LAST:event_txttsalAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu menu = new menu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new price().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel llname;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel txtcom;
    private javax.swing.JLabel txtpayroll;
    private javax.swing.JLabel txttsal;
    // End of variables declaration//GEN-END:variables
}
